### ISSUE TITLE
Add application health check settings

### ISSUE THREAD

**Issue by KaiWalter** [dapr-sandbox/dapr-shared#46]
Add [application health check settings](https://docs.dapr.io/operations/resiliency/health-checks/app-health/#configuring-app-health-checks) to configuration options

I suggest adding this block to `daprd` section in configuration values

```
daprd:
    app: ...
    appHealth:
      # -- Enables the app health checks
      enabled: false
      # -- Path that Dapr invokes for health probes when the app channel is HTTP (this value is ignored if the app channel is using gRPC)
      checkPath: "/healthz"
      # -- Number of seconds between each health probe
      probeInterval: 5
      # -- Timeout in milliseconds for health probe requests
      probeTimeout: 500
      # -- Max number of consecutive failures before the app is considered unhealthy
      threshold: 3
```

please assign to me
