### ISSUE TITLE
Shared not ready with dapr 1.14.4

### ISSUE THREAD

**Issue by luigirende** [dapr-sandbox/dapr-shared#56]
When I use the Helm chart and set the image tag to version 1.14.4 in the values, while I have installed Dapr system at 1.14.4 version, the pod (whether in Deployment or DaemonSet mode) does not run. I see that it gets stuck with the following log: "Fetching initial identity certificate," and then it restarts.

**Comment by luigirende** [comment]
@ujala-singh have you deploy dapr in the default namespace dapr-system?

**Comment by ujala-singh** [comment]
@luigirende Nope, I am deploying it in a custom namespace say `my-dapr`.

**Comment by luigirende** [comment]
@ujala-singh have you tried to set the property   

```
scheduler:
    address: dapr-scheduler-server-0.dapr-scheduler-server.dapr-system.svc.cluster.local:50006
```

changing the namespace with my-dapr?

**Comment by ujala-singh** [comment]
@luigirende Yes I did, I updated the below values:
```
scheduler:
    address: dapr-scheduler-server-0.dapr-scheduler-server.my-dapr.svc.cluster.local:50006
  controlPlane:
    # -- Namespace where Dapr Control Plane is.
    namespace: "my-dapr"
    # -- Trust Domain used by the Dapr Control Plane
    trustDomain: "cluster.local"
    # -- The Dapr Control Plane operator address.
    operator:
      address: dapr-api.my-dapr.svc.cluster.local
      port: 443
    # -- The Dapr Control Plane sentry address.
    sentry:
      address: dapr-sentry.my-dapr.svc.cluster.local
      port: 443
    # -- The Dapr Control Plane placement server address.
    placementServer:
      address: dapr-placement-server.my-dapr.svc.cluster.local
      port: 50005
```

**Comment by akotsarelation** [comment]
It appears that the issue is still present. In order to make the shared dapr instances start, I had to do the following manual fixes:

1. As noted in the issue above, the default configuration assumes ports 80 for some control plane components and they need to be overridden:
```
shared:
  controlPlane:
    sentryAddress: dapr-sentry.dapr-system.svc.cluster.local:443
    operatorAddress: dapr-api.dapr-system.svc.cluster.local:443
    placementServerAddress: dapr-placement-server.dapr-system.svc.cluster.local:50005
```

2. (BUG) The Helm chart adds the `DAPR_CONTROL_PLANE_NAMESPACE` env variable, when the correct name is `DAPR_CONTROLPLANE_NAMESPACE` (note lack of _ in CONTROLPLANE). See https://github.com/dapr/dapr/blob/88f467a2feef18defec06b1425b8229b27a18045/pkg/security/consts/consts.go#L47

There is no way to adjust this env variable via the chart values or add new custom environment variables.
